import type { Game } from './types';

export const games: Game[] = [
  {
    slug: '2048',
    category: 'puzzle',
    iframeUrl: '/games/2048/index.html',
    thumbnailEmoji: '🔢',
    translations: {
      en: { title: '2048', description: 'Merge tiles to reach the 2048 tile! A classic puzzle game where you combine numbers to create higher values.', instructions: 'Use arrow keys to slide tiles. Merge same numbers to create larger numbers. Reach 2048 to win!' },
      es: { title: '2048', description: '¡Combina fichas para llegar a 2048! Un clásico juego de puzzle donde combinas números para crear valores más altos.', instructions: 'Usa las teclas de dirección para deslizar fichas. Combina números iguales para crear números más grandes. ¡Alcanza 2048 para ganar!' },
      pt: { title: '2048', description: 'Combine blocos para chegar ao 2048! Um clássico jogo de quebra-cabeça onde você combina números para criar valores maiores.', instructions: 'Use as teclas de seta para deslizar blocos. Combine números iguais para criar números maiores. Chegue a 2048 para vencer!' },
    },
  },
  {
    slug: 'wordle-unlimited',
    category: 'puzzle',
    iframeUrl: '/games/wordleunlimited/index.html',
    thumbnailEmoji: '🔤',
    translations: {
      en: { title: 'Wordle Unlimited', description: 'Guess the hidden word in 6 tries. A popular word puzzle game that tests your vocabulary.', instructions: 'Type a 5-letter word and press enter. Green = correct letter in right position. Yellow = correct letter in wrong position. Gray = letter not in word.' },
      es: { title: 'Wordle Unlimited', description: 'Adivina la palabra oculta en 6 intentos. Un popular juego de palabras que pone a prueba tu vocabulario.', instructions: 'Escribe una palabra de 5 letras y presiona enter. Verde = letra correcta y posición correcta. Amarillo = letra correcta en posición incorrecta.' },
      pt: { title: 'Wordle Unlimited', description: 'Adivinhe a palavra oculta em 6 tentativas. Um popular jogo de palavras que testa seu vocabulário.', instructions: 'Digite uma palavra de 5 letras e pressione enter. Verde = letra correta na posição certa. Amarelo = letra correta na posição errada.' },
    },
  },
  {
    slug: 'trap-the-cat',
    category: 'puzzle',
    iframeUrl: '/games/trapthecat/index.html',
    thumbnailEmoji: '🐱',
    translations: {
      en: { title: 'Trap the Cat', description: 'A strategic puzzle game where you trap a cat by clicking on dots. Can you corner the clever feline?', instructions: 'Click on dots to block the cat\'s path. Trap the cat so it can\'t move. Plan your moves carefully!' },
      es: { title: 'Trap the Cat', description: 'Un juego de puzzle estratégico donde atrapas a un gato haciendo clic en puntos. ¿Puedes acorralar al felino?', instructions: 'Haz clic en los puntos para bloquear el camino del gato. Atrapa al gato para que no pueda moverse.' },
      pt: { title: 'Trap the Cat', description: 'Um jogo de quebra-cabeça estratégico onde você prende um gato clicando em pontos. Você consegue encurralar o felino?', instructions: 'Clique nos pontos para bloquear o caminho do gato. Prenda o gato para que não possa se mover.' },
    },
  },
  {
    slug: 'agariolite',
    category: 'casual',
    iframeUrl: '/games/agariolite/index.html',
    thumbnailEmoji: '🟣',
    translations: {
      en: { title: 'Agar.io Lite', description: 'A simplified version of the popular cell-eating game. Eat smaller cells, grow bigger, and avoid bigger ones!', instructions: 'Move your mouse to control your cell. Eat smaller colored cells to grow. Avoid larger cells that can eat you.' },
      es: { title: 'Agar.io Lite', description: 'Una versión simplificada del popular juego de comer células. Come células más pequeñas, crece y evita las más grandes.', instructions: 'Mueve el ratón para controlar tu célula. Come células de colores más pequeñas para crecer. Evita las células más grandes.' },
      pt: { title: 'Agar.io Lite', description: 'Uma versão simplificada do popular jogo de comer células. Coma células menores, cresça e evite as maiores!', instructions: 'Mova o mouse para controlar sua célula. Coma células coloridas menores para crescer. Evite células maiores.' },
    },
  },
  {
    slug: 'unicycle-hero',
    category: 'sports',
    iframeUrl: '/games/unicyclehero/index.html',
    thumbnailEmoji: '🚲',
    translations: {
      en: { title: 'Unicycle Hero', description: 'Balance on a unicycle and ride through challenging obstacles. A fun physics-based sports game.', instructions: 'Use arrow keys or tilt to maintain balance. Lean forward to move, lean back to slow down. Don\'t fall!' },
      es: { title: 'Unicycle Hero', description: 'Equilibra en un monociclo y atraviesa obstáculos desafiantes. Un divertido juego de deportes basado en física.', instructions: 'Usa las teclas de dirección para mantener el equilibrio. Inclínate hacia adelante para moverte, hacia atrás para frenar.' },
      pt: { title: 'Unicycle Hero', description: 'Equilibre em um monociclo e atravesse obstáculos desafiadores. Um divertido jogo de esportes baseado em física.', instructions: 'Use as teclas de seta para manter o equilíbrio. Incline-se para frente para mover, para trás para frear.' },
    },
  },
  {
    slug: 'wheelie-bike',
    category: 'sports',
    iframeUrl: '/games/wheeliebike/index.html',
    thumbnailEmoji: '🏍️',
    translations: {
      en: { title: 'Wheelie Bike', description: 'Perform stunts on your bike! Balance and ride to keep the wheelie going as long as possible.', instructions: 'Use up/down arrows to control balance. Lean back to do a wheelie. Keep balanced to ride further.' },
      es: { title: 'Wheelie Bike', description: '¡Haz acrobacias en tu bicicleta! Equilibra y conduce para mantener la rueda levantada el mayor tiempo posible.', instructions: 'Usa las flechas arriba/abajo para controlar el equilibrio. Inclínate hacia atrás para hacer un wheelie.' },
      pt: { title: 'Wheelie Bike', description: 'Faça manobras na sua bicicleta! Equilibre e ande para manter a roda dianteira levantada o máximo possível.', instructions: 'Use as setas cima/baixo para controlar o equilíbrio. Incline-se para trás para fazer wheelie.' },
    },
  },
  {
    slug: 'volley-random',
    category: 'sports',
    iframeUrl: '/games/volleyrandom/index.html',
    thumbnailEmoji: '🏐',
    translations: {
      en: { title: 'Volley Random', description: 'A fun volleyball game where you compete against the computer. Spike, serve, and score points!', instructions: 'Move your player with arrow keys. Press space to hit the ball. Time your jumps to spike the ball over the net.' },
      es: { title: 'Volley Random', description: 'Un divertido juego de voleibol donde compites contra la computadora. ¡Remata, sirve y anota puntos!', instructions: 'Mueve tu jugador con las teclas de dirección. Presiona espacio para golpear el balón.' },
      pt: { title: 'Volley Random', description: 'Um divertido jogo de vôlei onde você compete contra o computador. Corte, saque e marque pontos!', instructions: 'Mova seu jogador com as teclas de seta. Pressione espaço para bater na bola.' },
    },
  },
  {
    slug: '1on1-soccer',
    category: 'sports',
    iframeUrl: '/games/1on1soccer/index.html',
    thumbnailEmoji: '⚽',
    translations: {
      en: { title: '1 on 1 Soccer', description: 'Classic one-on-one soccer match. Dribble past your opponent and score goals in this fast-paced sports game.', instructions: 'Use arrow keys to move your player. Kick the ball towards the goal. First to 5 goals wins!' },
      es: { title: '1 on 1 Soccer', description: 'Partido de fútbol clásico uno contra uno. Regatea a tu oponente y marca goles en este rápido juego deportivo.', instructions: 'Usa las teclas de dirección para mover a tu jugador. Patea el balón hacia la portería.' },
      pt: { title: '1 on 1 Soccer', description: 'Partida clássica de futebol um contra um. Drible seu oponente e marque gols neste rápido jogo esportivo.', instructions: 'Use as teclas de seta para mover seu jogador. Chute a bola em direção ao gol.' },
    },
  },
  {
    slug: '1on1-tennis',
    category: 'sports',
    iframeUrl: '/games/1on1tennis/index.html',
    thumbnailEmoji: '🎾',
    translations: {
      en: { title: '1 on 1 Tennis', description: 'Play a classic tennis match against the computer. Serve, volley, and smash your way to victory!', instructions: 'Move your player with arrow keys. Press space to hit the ball. Time your swings for powerful shots.' },
      es: { title: '1 on 1 Tennis', description: 'Juega un partido de tenis clásico contra la computadora. ¡Saca, volea y remata tu camino a la victoria!', instructions: 'Mueve a tu jugador con las teclas de dirección. Presiona espacio para golpear la pelota.' },
      pt: { title: '1 on 1 Tennis', description: 'Jogue uma partida clássica de tênis contra o computador. Saque, voleie e ataque seu caminho para a vitória!', instructions: 'Mova seu jogador com as teclas de seta. Pressione espaço para bater na bola.' },
    },
  },
  {
    slug: 'trivia-crack',
    category: 'puzzle',
    iframeUrl: '/games/triviacrack/index.html',
    thumbnailEmoji: '🧠',
    translations: {
      en: { title: 'Trivia Crack', description: 'Test your knowledge across multiple categories. Answer questions correctly to win the game!', instructions: 'Read each question and select the correct answer. Answer enough questions to beat the opponent.' },
      es: { title: 'Trivia Crack', description: 'Pon a prueba tu conocimiento en múltiples categorías. ¡Responde preguntas correctamente para ganar!', instructions: 'Lee cada pregunta y selecciona la respuesta correcta. Responde suficientes preguntas para vencer al oponente.' },
      pt: { title: 'Trivia Crack', description: 'Teste seu conhecimento em várias categorias. Responda perguntas corretamente para vencer!', instructions: 'Leia cada pergunta e selecione a resposta correta. Responda perguntas suficientes para vencer o oponente.' },
    },
  },
  {
    slug: 'chasing-lights',
    category: 'action',
    iframeUrl: '/games/chasing-lights/index.html',
    thumbnailEmoji: '💡',
    translations: {
      en: { title: 'Chasing Lights', description: 'A fast-paced action game where you chase moving lights and avoid obstacles. Quick reflexes required!', instructions: 'Use mouse or keyboard to chase the lights. Collect all lights to complete each level.' },
      es: { title: 'Chasing Lights', description: 'Un juego de acción rápida donde persigues luces en movimiento y evitas obstáculos. ¡Se requieren reflejos rápidos!', instructions: 'Usa el ratón o teclado para perseguir las luces. Colecciona todas las luces para completar cada nivel.' },
      pt: { title: 'Chasing Lights', description: 'Um jogo de ação rápida onde você persegue luzes em movimento e evita obstáculos. Reflexos rápidos são necessários!', instructions: 'Use o mouse ou teclado para perseguir as luzes. Colete todas as luzes para completar cada nível.' },
    },
  },
  {
    slug: 'exterminator',
    category: 'action',
    iframeUrl: '/games/exterminator/index.html',
    thumbnailEmoji: '🔫',
    translations: {
      en: { title: 'Exterminator', description: 'Blast away waves of enemies in this action-packed shooter game. Aim, shoot, and survive!', instructions: 'Use mouse to aim, click to shoot. Move with WASD or arrow keys. Survive waves of enemies.' },
      es: { title: 'Exterminator', description: '¡Explota oleadas de enemigos en este juego de disparos lleno de acción. Apunta, dispara y sobrevive!', instructions: 'Usa el ratón para apuntar, haz clic para disparar. Muévete con WASD o flechas. Sobrevive oleadas de enemigos.' },
      pt: { title: 'Exterminator', description: 'Elimine ondas de inimigos neste jogo de tiro cheio de ação. Mire, atire e sobreviva!', instructions: 'Use o mouse para mirar, clique para atirar. Mova-se com WASD ou setas. Sobreviva a ondas de inimigos.' },
    },
  },
  {
    slug: 'skull-ocean',
    category: 'action',
    iframeUrl: '/games/skull-ocean/index.html',
    thumbnailEmoji: '💀',
    translations: {
      en: { title: 'Skull Ocean', description: 'Navigate treacherous waters filled with danger in this action-adventure game.', instructions: 'Use arrow keys to navigate your ship. Avoid obstacles and enemies. Collect treasures to score.' },
      es: { title: 'Skull Ocean', description: 'Navega por aguas traicioneras llenas de peligro en este juego de acción y aventura.', instructions: 'Usa las teclas de dirección para navegar tu barco. Evita obstáculos y enemigos. Colecciona tesoros.' },
      pt: { title: 'Skull Ocean', description: 'Navegue por águas traiçoeiras cheias de perigo neste jogo de ação e aventura.', instructions: 'Use as teclas de seta para navegar seu navio. Evite obstáculos e inimigos. Colete tesouros.' },
    },
  },
  {
    slug: 'spacepi',
    category: 'action',
    iframeUrl: '/games/spacepi/index.html',
    thumbnailEmoji: '🌌',
    translations: {
      en: { title: 'SpacePi', description: 'Defend your bases in space! A mouse accuracy and agility game by jackrugile, originally for js13k.', instructions: 'Use mouse to aim and click to shoot. Protect your bases from incoming asteroids and enemies.' },
      es: { title: 'SpacePi', description: '¡Defiende tus bases en el espacio! Un juego de precisión del ratón que desafía tu agilidad.', instructions: 'Usa el ratón para apuntar y haz clic para disparar. Protege tus bases de asteroides y enemigos.' },
      pt: { title: 'SpacePi', description: 'Defenda suas bases no espaço! Um jogo de precisão do mouse que desafia sua agilidade.', instructions: 'Use o mouse para mirar e clique para atirar. Proteja suas bases de asteroides e inimigos.' },
    },
  },
  {
    slug: 'stolen-sword',
    category: 'action',
    iframeUrl: '/games/stolen-sword/index.html',
    thumbnailEmoji: '🗡️',
    translations: {
      en: { title: 'Stolen Sword', description: 'Embark on a quest to recover a stolen sword. Fight enemies and explore in this action adventure.', instructions: 'Use arrow keys to move. Press space or Z to attack. Defeat enemies and find the stolen sword.' },
      es: { title: 'Stolen Sword', description: 'Embárcate en una búsqueda para recuperar una espada robada. ¡Combate enemigos y explora en esta aventura!', instructions: 'Usa las teclas de dirección para moverte. Presiona espacio o Z para atacar. Derrota enemigos.' },
      pt: { title: 'Stolen Sword', description: 'Embarque em uma missão para recuperar uma espada roubada. Lute contra inimigos e explore nesta aventura!', instructions: 'Use as teclas de seta para mover. Pressione espaço ou Z para atacar. Derrote inimigos.' },
    },
  },
  {
    slug: 'sushi-kitchen',
    category: 'casual',
    iframeUrl: '/games/sushi-kitchen/index.html',
    thumbnailEmoji: '🍣',
    translations: {
      en: { title: 'Sushi Kitchen', description: 'Run your own sushi restaurant! Prepare and serve sushi dishes to hungry customers as fast as you can.', instructions: 'Follow recipe instructions. Click ingredients and combine them in the right order. Serve dishes quickly for tips!' },
      es: { title: 'Sushi Kitchen', description: '¡Gestiona tu propio restaurante de sushi! Prepara y sirve platos de sushi a clientes hambrientos lo más rápido posible.', instructions: 'Sigue las instrucciones de la receta. Haz clic en los ingredientes y combínalos en el orden correcto.' },
      pt: { title: 'Sushi Kitchen', description: 'Gerencie seu próprio restaurante de sushi! Prepare e sirva pratos de sushi para clientes famintos o mais rápido possível.', instructions: 'Siga as instruções da receita. Clique nos ingredientes e combine-os na ordem correta.' },
    },
  },
  {
    slug: 'sword-art-offline',
    category: 'action',
    iframeUrl: '/games/sword-art-offline/index.html',
    thumbnailEmoji: '⚔️',
    translations: {
      en: { title: 'Sword Art Offline', description: 'A simple sword fighting game where you battle enemies in an arena. Slash, dodge, and conquer!', instructions: 'Use arrow keys to move. Press Z or X to attack with your sword. Defeat all enemies to win.' },
      es: { title: 'Sword Art Offline', description: 'Un simple juego de lucha con espadas donde combates enemigos en una arena. ¡Corta, esquiva y conquista!', instructions: 'Usa las teclas de dirección para moverte. Presiona Z o X para atacar con tu espada.' },
      pt: { title: 'Sword Art Offline', description: 'Um simples jogo de luta com espadas onde você batalha inimigos em uma arena. Corte, desvie e conquiste!', instructions: 'Use as teclas de seta para mover. Pressione Z ou X para atacar com sua espada.' },
    },
  },
  {
    slug: 'triska',
    category: 'puzzle',
    iframeUrl: '/games/triska/index.html',
    thumbnailEmoji: '🔺',
    translations: {
      en: { title: 'Triska', description: 'A triangular puzzle game where you match and clear shapes. A fresh take on classic matching gameplay.', instructions: 'Click on adjacent triangles of the same color to clear them. Clear groups to score points.' },
      es: { title: 'Triska', description: 'Un juego de puzzle triangular donde emparejas y limpias formas. Una nueva versión del juego de emparejar clásico.', instructions: 'Haz clic en triángulos adyacentes del mismo color para limpiarlos. Limpia grupos para ganar puntos.' },
      pt: { title: 'Triska', description: 'Um jogo de quebra-cabeça triangular onde você combina e limpa formas. Uma nova versão do jogo clássico de combinar.', instructions: 'Clique em triângulos adjacentes da mesma cor para limpá-los. Limpe grupos para ganhar pontos.' },
    },
  },

  {
    slug: 'black-hole-square',
    category: 'puzzle',
    iframeUrl: '/games/Black%20hole%20square/index.html',
    thumbnailEmoji: '🕳️',
    translations: {
      en: { title: 'Black Hole Square', description: 'Clean the universe in this puzzle game! Use your black hole to absorb all matter in each level.', instructions: 'Click or tap to move your black hole. Absorb smaller objects to grow bigger. Avoid or consume larger objects carefully.' },
      es: { title: 'Black Hole Square', description: '¡Limpia el universo en este juego de puzzles! Usa tu agujero negro para absorber toda la materia en cada nivel.', instructions: 'Haz clic o toca para mover tu agujero negro. Absorbe objetos pequeños para crecer.' },
      pt: { title: 'Black Hole Square', description: 'Limpe o universo neste jogo de quebra-cabeça! Use seu buraco negro para absorver toda matéria em cada nível.', instructions: 'Clique ou toque para mover seu buraco negro. Absorva objetos menores para crescer.' },
    },
  },
  {
    slug: 'chromaincident',
    category: 'action',
    iframeUrl: '/games/Chromaincident/index.html',
    thumbnailEmoji: '🌈',
    translations: {
      en: { title: 'Chromaincident', description: 'An intense arcade action game with vibrant colors. Dodge obstacles and survive as long as possible.', instructions: 'Use arrow keys or WASD to move. Avoid enemies and obstacles. Survive as long as you can!' },
      es: { title: 'Chromaincident', description: 'Un intenso juego de acción arcade con colores vibrantes. Esquiva obstáculos y sobrevive el mayor tiempo posible.', instructions: 'Usa las teclas de dirección o WASD para moverte. Evita enemigos y obstáculos.' },
      pt: { title: 'Chromaincident', description: 'Um intenso jogo de ação arcade com cores vibrantes. Desvie de obstáculos e sobreviva o máximo possível.', instructions: 'Use as teclas de seta ou WASD para mover. Evite inimigos e obstáculos.' },
    },
  },
  {
    slug: 'bitlife',
    category: 'casual',
    iframeUrl: '/games/bitlife/index.html',
    thumbnailEmoji: '🧬',
    translations: {
      en: { title: 'BitLife', description: 'A life simulation game where your choices shape your character\'s destiny. Career, relationships, and more!', instructions: 'Tap or click to make choices. Each decision affects your character\'s stats like health, happiness, and wealth.' },
      es: { title: 'BitLife', description: 'Un juego de simulación de vida donde tus decisiones moldean el destino de tu personaje.', instructions: 'Toca o haz clic para tomar decisiones. Cada decisión afecta las estadísticas de tu personaje.' },
      pt: { title: 'BitLife', description: 'Um jogo de simulação de vida onde suas escolhas moldam o destino do seu personagem.', instructions: 'Toque ou clique para fazer escolhas. Cada decisão afeta as estatísticas do seu personagem.' },
    },
  },
  {
    slug: 'evil-glitch',
    category: 'action',
    iframeUrl: '/games/evilGlitch/index.html',
    thumbnailEmoji: '👾',
    translations: {
      en: { title: 'Evil Glitch', description: 'A glitch-themed action game where you fight corrupted data and digital enemies.', instructions: 'Use arrow keys to move. Press space to attack. Defeat all corrupted data to clear each level.' },
      es: { title: 'Evil Glitch', description: 'Un juego de acción con temática de fallos donde luchas contra datos corruptos y enemigos digitales.', instructions: 'Usa las teclas de dirección para moverte. Presiona espacio para atacar.' },
      pt: { title: 'Evil Glitch', description: 'Um jogo de ação com tema de falhas onde você luta contra dados corrompidos e inimigos digitais.', instructions: 'Use as teclas de seta para mover. Pressione espaço para atacar.' },
    },
  },
  {
    slug: 'konnekt',
    category: 'strategy',
    iframeUrl: '/games/konnekt/index.html',
    thumbnailEmoji: '🔗',
    translations: {
      en: { title: 'Konnekt', description: 'A strategic JS13k game. Connect nodes on a 3D sphere, expand your network, and dominate!', instructions: 'Drag from blue nodes to red enemy nodes to attack. Drag empty space to rotate the sphere.' },
      es: { title: 'Konnekt', description: 'Un juego de estrategia JS13k. Conecta nodos en una esfera 3D, expande tu red y domina.', instructions: 'Arrastra desde nodos azules a nodos rojos enemigos para atacar. Arrastra espacio vacío para girar.' },
      pt: { title: 'Konnekt', description: 'Um jogo de estratégia JS13k. Conecte nós em uma esfera 3D, expanda sua rede e domine!', instructions: 'Arraste de nós azuis para nós vermelhos inimigos para atacar. Arraste espaço vazio para girar.' },
    },
  },
  {
    slug: 'retrohaunt',
    category: 'action',
    iframeUrl: '/games/retrohaunt/index.html',
    thumbnailEmoji: '👻',
    translations: {
      en: { title: 'RetroHaunt', description: 'A retro-styled action game where you hunt ghosts in a haunted mansion.', instructions: 'Use arrow keys or WASD to move. Press space to capture ghosts. Avoid ghost attacks.' },
      es: { title: 'RetroHaunt', description: 'Un juego de acción retro donde cazas fantasmas en una mansión embrujada.', instructions: 'Usa las teclas de dirección o WASD para moverte. Presiona espacio para capturar fantasmas.' },
      pt: { title: 'RetroHaunt', description: 'Um jogo de ação retro onde você caça fantasmas em uma mansão assombrada.', instructions: 'Use as teclas de seta ou WASD para mover. Pressione espaço para capturar fantasmas.' },
    },
  },
  {
    slug: 'xx142-b2exe',
    category: 'action',
    iframeUrl: '/games/xx142-b2exe/index.html',
    thumbnailEmoji: '🤖',
    translations: {
      en: { title: 'xx142-b2.exe', description: 'A sci-fi action game where you play as a rogue AI escaping containment.', instructions: 'Use arrow keys to move. Press Z to interact or shoot. Survive security protocols and reach the exit.' },
      es: { title: 'xx142-b2.exe', description: 'Un juego de acción sci-fi donde eres una IA rebelde escapando de su confinamiento.', instructions: 'Usa las teclas de dirección para moverte. Presiona Z para interactuar o disparar.' },
      pt: { title: 'xx142-b2.exe', description: 'Um jogo de ação sci-fi onde você é uma IA rebelde escapando do confinamento.', instructions: 'Use as teclas de seta para mover. Pressione Z para interagir ou atirar.' },
    },
  },
  {
    slug: '2048cupcakes',
    category: 'puzzle',
    iframeUrl: '/games/2048cupcakes/index.html',
    thumbnailEmoji: '🧁',
    translations: {
      en: { title: '2048 Cupcakes', description: 'A delicious twist on 2048! Merge cupcake-themed tiles instead of numbers.', instructions: 'Use arrow keys to slide tiles. Merge same cupcakes to create new flavors. Reach the ultimate cupcake!' },
      es: { title: '2048 Cupcakes', description: '¡Una variante deliciosa de 2048! Combina fichas temáticas de cupcakes.', instructions: 'Usa las teclas de dirección para deslizar fichas. Combina cupcakes iguales para crear nuevos sabores.' },
      pt: { title: '2048 Cupcakes', description: 'Uma variação deliciosa do 2048! Combine blocos temáticos de cupcakes.', instructions: 'Use as teclas de seta para deslizar blocos. Combine cupcakes iguais para criar novos sabores.' },
    },
  },
  {
    slug: '8-ball-classic',
    category: 'sports',
    iframeUrl: '/games/8ballclassic/index.html',
    thumbnailEmoji: '🎱',
    translations: {
      en: { title: '8 Ball Classic', description: 'Play classic 8-ball pool against the computer. Sink all your balls then the 8-ball to win!', instructions: 'Aim with mouse, click and drag to set power, release to shoot. Sink your balls (stripes or solids) then the 8-ball.' },
      es: { title: '8 Ball Classic', description: 'Juega al billar clásico contra la computadora. ¡Hunde tus bolas y luego la 8 para ganar!', instructions: 'Apunta con el ratón, arrastra para ajustar la potencia, suelta para disparar.' },
      pt: { title: '8 Ball Classic', description: 'Jogue sinuca clássica contra o computador. Afunde suas bolas e depois a bola 8 para vencer!', instructions: 'Mire com o mouse, arraste para ajustar a força, solte para jogar.' },
    },
  },
  {
    slug: 'among-us',
    category: 'casual',
    iframeUrl: '/games/amongus/index.html',
    thumbnailEmoji: '🔴',
    translations: {
      en: { title: 'Among Us', description: 'A simplified Among Us experience. Complete tasks and figure out who the imposter is!', instructions: 'Click to move around the ship. Complete tasks marked on your list. Report bodies and vote out imposters.' },
      es: { title: 'Among Us', description: 'Una versión simplificada de Among Us. ¡Completa tareas y descubre quién es el impostor!', instructions: 'Haz clic para moverte por la nave. Completa las tareas marcadas en tu lista.' },
      pt: { title: 'Among Us', description: 'Uma versão simplificada de Among Us. Complete tarefas e descubra quem é o impostor!', instructions: 'Clique para se mover pela nave. Complete as tarefas marcadas na sua lista.' },
    },
  },
  {
    slug: 'bloxorz',
    category: 'puzzle',
    iframeUrl: '/games/bloxorz/index.html',
    thumbnailEmoji: '📦',
    translations: {
      en: { title: 'Bloxorz', description: 'A challenging puzzle game where you roll a block through a maze to reach the hole.', instructions: 'Use arrow keys to roll the block. Maneuver it into the square hole to advance. Plan each move carefully!' },
      es: { title: 'Bloxorz', description: 'Un desafiante juego de puzzle donde haces rodar un bloque a través de un laberinto.', instructions: 'Usa las teclas de dirección para rodar el bloque. Maniobra hacia el agujero cuadrado para avanzar.' },
      pt: { title: 'Bloxorz', description: 'Um desafiador jogo de quebra-cabeça onde você rola um bloco através de um labirinto.', instructions: 'Use as teclas de seta para rolar o bloco. Manobre-o até o buraco quadrado para avançar.' },
    },
  },
  {
    slug: 'candy-crush',
    category: 'puzzle',
    iframeUrl: '/games/candycrush/index.html',
    thumbnailEmoji: '🍬',
    translations: {
      en: { title: 'Candy Crush', description: 'Match colorful candies in this addictive puzzle game. Swap and match to clear the board!', instructions: 'Click and drag to swap adjacent candies. Match 3 or more of the same color to clear them.' },
      es: { title: 'Candy Crush', description: '¡Combina caramelos de colores en este adictivo juego de puzzle. Intercambia y combina para limpiar el tablero!', instructions: 'Haz clic y arrastra para intercambiar caramelos adyacentes. Combina 3 o más del mismo color.' },
      pt: { title: 'Candy Crush', description: 'Combine doces coloridos neste viciante jogo de quebra-cabeça. Troque e combine para limpar o tabuleiro!', instructions: 'Clique e arraste para trocar doces adjacentes. Combine 3 ou mais da mesma cor para limpá-los.' },
    },
  },
  {
    slug: 'chess',
    category: 'strategy',
    iframeUrl: '/games/chess/index.html',
    thumbnailEmoji: '♟️',
    translations: {
      en: { title: 'Chess', description: 'Play the classic game of chess against the computer. Test your strategic thinking!', instructions: 'Click a piece to select it, then click a square to move. Capture enemy pieces and checkmate the king.' },
      es: { title: 'Chess', description: 'Juega al ajedrez clásico contra la computadora. ¡Pon a prueba tu pensamiento estratégico!', instructions: 'Haz clic en una pieza para seleccionarla, luego haz clic en un cuadrado para moverla.' },
      pt: { title: 'Chess', description: 'Jogue o clássico jogo de xadrez contra o computador. Teste seu pensamento estratégico!', instructions: 'Clique em uma peça para selecioná-la, depois clique em um quadrado para mover.' },
    },
  },
  {
    slug: 'doodle-jump',
    category: 'action',
    iframeUrl: '/games/doodlejump/index.html',
    thumbnailEmoji: '🦘',
    translations: {
      en: { title: 'Doodle Jump', description: 'Guide the doodle jumper up an endless series of platforms. Jump higher and higher!', instructions: 'Tilt or use arrow keys to move left and right. Jump on platforms to go higher. Avoid obstacles and monsters.' },
      es: { title: 'Doodle Jump', description: 'Guía al saltarín por una serie interminable de plataformas. ¡Salta cada vez más alto!', instructions: 'Inclina o usa las flechas para moverte. Salta en plataformas para subir. Evita obstáculos.' },
      pt: { title: 'Doodle Jump', description: 'Guie o saltador por uma série interminável de plataformas. Pule cada vez mais alto!', instructions: 'Incline ou use as setas para mover. Pule em plataformas para subir. Evite obstáculos.' },
    },
  },
  {
    slug: 'flappy-bird',
    category: 'action',
    iframeUrl: '/games/flappybird/index.html',
    thumbnailEmoji: '🐦',
    translations: {
      en: { title: 'Flappy Bird', description: 'Tap to fly through pipes in this notoriously challenging game. How far can you go?', instructions: 'Click or press space to flap. Navigate through the gaps in the pipes. Don\'t hit the ground or pipes!' },
      es: { title: 'Flappy Bird', description: 'Toca para volar a través de tuberías en este notoriamente desafiante juego. ¿Hasta dónde puedes llegar?', instructions: 'Haz clic o presiona espacio para aletear. Navega por los espacios entre las tuberías.' },
      pt: { title: 'Flappy Bird', description: 'Toque para voar através de canos neste jogo notoriamente desafiador. Até onde você pode chegar?', instructions: 'Clique ou pressione espaço para voar. Navegue pelos espaços entre os canos.' },
    },
  },
  {
    slug: 'minesweeper',
    category: 'puzzle',
    iframeUrl: '/games/minesweeper/index.html',
    thumbnailEmoji: '💣',
    translations: {
      en: { title: 'Minesweeper', description: 'The classic logic puzzle game. Clear the minefield without detonating any mines!', instructions: 'Click to reveal a cell. Right-click to flag a mine. Numbers show how many mines are adjacent. Clear all safe cells to win.' },
      es: { title: 'Minesweeper', description: 'El clásico juego de puzzle de lógica. ¡Limpia el campo minado sin detonar minas!', instructions: 'Haz clic para revelar una celda. Click derecho para marcar una mina. Los números muestran minas adyacentes.' },
      pt: { title: 'Minesweeper', description: 'O clássico jogo de quebra-cabeça de lógica. Limpe o campo minado sem detonar minas!', instructions: 'Clique para revelar uma célula. Clique direito para marcar uma mina.' },
    },
  },
  {
    slug: 'pacman',
    category: 'action',
    iframeUrl: '/games/pacman/index.html',
    thumbnailEmoji: '👻',
    translations: {
      en: { title: 'Pac-Man', description: 'The arcade classic! Eat all the dots while avoiding ghosts. Power pellets let you turn the tables!', instructions: 'Use arrow keys to move Pac-Man. Eat all dots to clear the level. Eat power pellets to chase ghosts.' },
      es: { title: 'Pac-Man', description: '¡El clásico arcade! Come todos los puntos mientras evitas fantasmas. ¡Los puntos de poder te permiten dar la vuelta!', instructions: 'Usa las flechas para mover a Pac-Man. Come todos los puntos para limpiar el nivel.' },
      pt: { title: 'Pac-Man', description: 'O clássico arcade! Coma todos os pontos enquanto evita fantasmas. As pílulas de poder viram o jogo!', instructions: 'Use as setas para mover o Pac-Man. Coma todos os pontos para limpar a fase.' },
    },
  },
  {
    slug: 'stack',
    category: 'casual',
    iframeUrl: '/games/stack/index.html',
    thumbnailEmoji: '📐',
    translations: {
      en: { title: 'Stack', description: 'Stack blocks as high as you can! A simple but addictive game of precision and timing.', instructions: 'Click to drop the moving block. Align it perfectly with the stack below. Each miss makes the block smaller!' },
      es: { title: 'Stack', description: '¡Apila bloques lo más alto que puedas! Un juego simple pero adictivo de precisión.', instructions: 'Haz clic para dejar caer el bloque. Alinéalo perfectamente con la pila de abajo.' },
      pt: { title: 'Stack', description: 'Empilhe blocos o mais alto que puder! Um jogo simples mas viciante de precisão.', instructions: 'Clique para soltar o bloco. Alinhe-o perfeitamente com a pilha abaixo.' },
    },
  },
  {
    slug: 'retro-bowl',
    category: 'sports',
    iframeUrl: '/games/retrobowl/index.html',
    thumbnailEmoji: '🏈',
    translations: {
      en: { title: 'Retro Bowl', description: 'Manage and play as your own football team in this retro-styled sports game.', instructions: 'Swipe to throw the ball, control your quarterback, and lead your team to victory!' },
      es: { title: 'Retro Bowl', description: 'Gestiona y juega con tu propio equipo de fútbol americano en este deportivo juego retro.', instructions: 'Desliza para lanzar el balón, controla tu mariscal de campo y lleva a tu equipo a la victoria.' },
      pt: { title: 'Retro Bowl', description: 'Gerencie e jogue com seu próprio time de futebol americano neste jogo esportivo retro.', instructions: 'Deslize para lançar a bola, controle seu quarterback e lidere seu time à vitória!' },
    },
  },
  {
    slug: 'run-2',
    category: 'action',
    iframeUrl: '/games/run2/index.html',
    thumbnailEmoji: '🏃',
    translations: {
      en: { title: 'Run 2', description: 'Run and jump through space tunnels! Avoid obstacles and keep moving forward in this endless runner.', instructions: 'Use arrow keys or swipe to move left/right and jump. Avoid obstacles and collect power-ups.' },
      es: { title: 'Run 2', description: '¡Corre y salta a través de túneles espaciales! Evita obstáculos y sigue moviéndote hacia adelante.', instructions: 'Usa las flechas para moverte izquierda/derecha y saltar. Evita obstáculos.' },
      pt: { title: 'Run 2', description: 'Corra e pule através de túneis espaciais! Evite obstáculos e continue se movendo para frente.', instructions: 'Use as setas para mover esquerda/direita e pular. Evite obstáculos.' },
    },
  },
  {
    slug: 'stickman-hook',
    category: 'action',
    iframeUrl: '/games/stickmanhook/index.html',
    thumbnailEmoji: '🪝',
    translations: {
      en: { title: 'Stickman Hook', description: 'Swing like Spider-Man! Use your hook to swing from point to point in this physics-based game.', instructions: 'Click to hook onto a point. Swing your stickman to gain momentum. Release at the right time to fly forward.' },
      es: { title: 'Stickman Hook', description: '¡Columpiate como Spider-Man! Usa tu gancho para balancearte de punto a punto.', instructions: 'Haz clic para engancharte a un punto. Balancea a tu stickman para ganar impulso.' },
      pt: { title: 'Stickman Hook', description: 'Balance como o Homem-Aranha! Use seu gancho para balançar de ponto a ponto.', instructions: 'Clique para se prender a um ponto. Balance seu stickman para ganhar impulso.' },
    },
  },
  {
    slug: 'tiny-fishing',
    category: 'casual',
    iframeUrl: '/games/tinyfishing/index.html',
    thumbnailEmoji: '🎣',
    translations: {
      en: { title: 'Tiny Fishing', description: 'Cast your line and catch fish in this relaxing fishing game. Upgrade your gear for bigger catches!', instructions: 'Click to cast your line. Wait for a fish to bite, then click to reel it in. Earn money to upgrade.' },
      es: { title: 'Tiny Fishing', description: 'Lanza tu caña y pesca peces en este relajante juego de pesca. ¡Mejora tu equipo para capturas más grandes!', instructions: 'Haz clic para lanzar tu caña. Espera a que un pez muerda, luego haz clic para recoger.' },
      pt: { title: 'Tiny Fishing', description: 'Lance sua linha e pesque peixes neste relaxante jogo de pesca. Melhore seu equipamento!', instructions: 'Clique para lançar sua linha. Espere um peixe morder, então clique para puxar.' },
    },
  },
  {
    slug: 'worlds-hardest-game',
    category: 'action',
    iframeUrl: '/games/worldshardestgame/index.html',
    thumbnailEmoji: '🏆',
    translations: {
      en: { title: 'World\'s Hardest Game', description: 'Navigate a red square through levels filled with moving blue balls. It\'s as hard as it sounds!', instructions: 'Use arrow keys to move your red square. Reach the green zone to complete each level. Don\'t touch the blue balls!',
        guide: '**Level 1-5 Beginner Tips:** Study enemy patterns before moving. Wait at the edge of each obstacle and time your dash between enemies. Short, precise movements work better than rushing. Use the walls as safe spots to catch your breath.\n\n**Advanced Strategy:** Memorize enemy spawn points. The game is 100% pattern-based - no randomness. Each failure teaches you where NOT to be. Take 10 seconds to observe before your first move on each new level.' },
      es: { title: 'World\'s Hardest Game', description: 'Navega un cuadrado rojo a través de niveles llenos de bolas azules en movimiento. ¡Es tan difícil como suena!', instructions: 'Usa las flechas para mover tu cuadrado rojo. Llega a la zona verde para completar cada nivel.',
        guide: '**Consejos Niveles 1-5:** Estudia los patrones enemigos antes de moverte. Espera al borde de cada obstáculo y cruza entre enemigos con precisión. Movimientos cortos y precisos funcionan mejor que apresurarse.\n\n**Estrategia Avanzada:** Memoriza los puntos de aparición. El juego es 100% basado en patrones - no hay aleatoriedad. Tómate 10 segundos para observar antes de moverte.' },
      pt: { title: 'World\'s Hardest Game', description: 'Navegue um quadrado vermelho através de níveis cheios de bolas azuis em movimento. É tão difícil quanto parece!', instructions: 'Use as setas para mover seu quadrado vermelho. Alcance a zona verde para completar cada nível.',
        guide: '**Dicas Níveis 1-5:** Estude os padrões inimigos antes de se mover. Espere na borda de cada obstáculo e cruze entre inimigos com precisão. Movimentos curtos e precisos são melhores que pressa.\n\n**Estratégia Avançada:** Memorize os pontos de aparecimento. O jogo é 100% baseado em padrões - não há aleatoriedade.' },
    },
  },
  {
    slug: 'zombie-rush',
    category: 'action',
    iframeUrl: '/games/zombierush/index.html',
    thumbnailEmoji: '🧟',
    translations: {
      en: { title: 'Zombie Rush', description: 'Survive the zombie apocalypse! Shoot waves of zombies and stay alive as long as possible.', instructions: 'Use mouse to aim and click to shoot. Move with WASD or arrow keys. Survive as many waves as possible.' },
      es: { title: 'Zombie Rush', description: '¡Sobrevive al apocalipsis zombie! Dispara oleadas de zombies y mantente con vida el mayor tiempo posible.', instructions: 'Usa el ratón para apuntar y haz clic para disparar. Muévete con WASD o flechas.' },
      pt: { title: 'Zombie Rush', description: 'Sobreviva ao apocalipse zumbi! Atire em ondas de zumbis e fique vivo o máximo possível.', instructions: 'Use o mouse para mirar e clique para atirar. Mova-se com WASD ou setas.' },
    },
  },
  {
    slug: 'bad-ice-cream-2',
    category: 'casual',
    iframeUrl: '/games/badicecream2/index.html',
    thumbnailEmoji: '🍦',
    translations: {
      en: { title: 'Bad Ice Cream 2', description: 'Collect ice cream ingredients while avoiding the monsters! A fun 2D arcade game.', instructions: 'Use arrow keys to move. Collect all fruits to complete the level. Avoid monsters or trap them in walls.' },
      es: { title: 'Bad Ice Cream 2', description: '¡Colecciona ingredientes de helado mientras evitas monstruos! Un divertido juego arcade 2D.', instructions: 'Usa las flechas para moverte. Colecciona todas las frutas para completar el nivel.' },
      pt: { title: 'Bad Ice Cream 2', description: 'Colete ingredientes de sorvete enquanto evita monstros! Um divertido jogo arcade 2D.', instructions: 'Use as setas para mover. Colete todas as frutas para completar o nível.' },
    },
  },
  {
    slug: 'beta-1-3',
    category: 'casual',
    iframeUrl: '/games/Beta_1.3/index.html',
    thumbnailEmoji: '⛏️',
    translations: {
    en: { title: 'Minecraft Beta 1.3', description: 'Explore a blocky world in this classic Minecraft Beta 1.3 recreation. Build, mine, and survive!', instructions: 'WASD to move, space to jump. Left click to break blocks, right click to place. E to open inventory.' },
      es: { title: 'Minecraft Beta 1.3', description: 'Explora un mundo de bloques en esta clásica recreación de Minecraft Beta 1.3. ¡Construye, mina y sobrevive!', instructions: 'WASD para moverte, espacio para saltar. Click izquierdo para romper bloques.' },
      pt: { title: 'Minecraft Beta 1.3', description: 'Explore um mundo de blocos nesta clássica recriação do Minecraft Beta 1.3. Construa, minere e sobreviva!', instructions: 'WASD para mover, espaço para pular. Clique esquerdo para quebrar blocos.' },
    },
  },
  {
    slug: 'indev',
    category: 'casual',
    iframeUrl: '/games/Indev/index.html',
    thumbnailEmoji: '🟫',
    translations: {
      en: { title: 'Minecraft Indev', description: 'An early Minecraft Indev version recreation. Experience the origins of the block-building phenomenon!', instructions: 'WASD to move, space to jump. Click to break and place blocks. Explore the infinite world.' },
      es: { title: 'Minecraft Indev', description: 'Una recreación de la versión Indev de Minecraft. ¡Experimenta los orígenes del fenómeno de construcción de bloques!', instructions: 'WASD para moverte, espacio para saltar. Haz clic para romper y colocar bloques.' },
      pt: { title: 'Minecraft Indev', description: 'Uma recriação da versão Indev do Minecraft. Experimente as origens do fenômeno de construção de blocos!', instructions: 'WASD para mover, espaço para pular. Clique para quebrar e colocar blocos.' },
    },
  },
  {
    slug: 'clash-of-vikings',
    category: 'action',
    iframeUrl: '/games/clashofvikings/index.html',
    thumbnailEmoji: '🛡️',
    translations: {
      en: { title: 'Clash of Vikings', description: 'Lead your Viking warriors into battle! Build your army and conquer enemy territories.', instructions: 'Click to send your warriors. Upgrade your units between rounds. Defeat all enemies to win.' },
      es: { title: 'Clash of Vikings', description: '¡Lidera a tus guerreros vikingos a la batalla! Construye tu ejército y conquista territorios enemigos.', instructions: 'Haz clic para enviar a tus guerreros. Mejora tus unidades entre rondas.' },
      pt: { title: 'Clash of Vikings', description: 'Lidere seus guerreiros vikings na batalha! Construa seu exército e conquiste territórios inimigos.', instructions: 'Clique para enviar seus guerreiros. Melhore suas unidades entre as rodadas.' },
    },
  },
  {
    slug: 'sand-game',
    category: 'casual',
    iframeUrl: '/games/sandgame/index.html',
    thumbnailEmoji: '🏖️',
    translations: {
      en: { title: 'Sand Game', description: 'A relaxing sand physics simulation. Draw different materials and watch them interact!', instructions: 'Click and drag to draw sand. Different colors create different materials. Watch the physics simulation at work.' },
      es: { title: 'Sand Game', description: 'Una relajante simulación de física de arena. ¡Dibuja diferentes materiales y mira cómo interactúan!', instructions: 'Haz clic y arrastra para dibujar arena. Diferentes colores crean diferentes materiales.' },
      pt: { title: 'Sand Game', description: 'Uma relaxante simulação de física de areia. Desenhe diferentes materiais e veja-os interagir!', instructions: 'Clique e arraste para desenhar areia. Cores diferentes criam materiais diferentes.' },
    },
  },
  {
    slug: 'territorial-io',
    category: 'strategy',
    iframeUrl: '/games/territorialio/index.html',
    thumbnailEmoji: '🗺️',
    translations: {
      en: { title: 'Territorial.io', description: 'Expand your territory by conquering neighboring lands. A strategic battle for dominance!', instructions: 'Click on your territory then click on an adjacent enemy territory to attack. Build up your army to conquer larger areas.' },
      es: { title: 'Territorial.io', description: 'Expande tu territorio conquistando tierras vecinas. ¡Una batalla estratégica por el dominio!', instructions: 'Haz clic en tu territorio y luego en un territorio enemigo adyacente para atacar.' },
      pt: { title: 'Territorial.io', description: 'Expanda seu território conquistando terras vizinhas. Uma batalha estratégica pelo domínio!', instructions: 'Clique em seu território e depois em um território inimigo adjacente para atacar.' },
    },
  },
  {
    slug: 'bubble-shooter',
    category: 'puzzle',
    iframeUrl: '/games/bubbleshooter/index.html',
    thumbnailEmoji: '🫧',
    translations: {
      en: { title: 'Bubble Shooter', description: 'Aim and shoot bubbles to match 3 or more! A classic bubble popping puzzle game.', instructions: 'Aim with your mouse, click to shoot. Match 3 or more bubbles of the same color to pop them. Clear all bubbles to win.' },
      es: { title: 'Bubble Shooter', description: '¡Apunta y dispara burbujas para juntar 3 o más! Un clásico juego de puzzle de burbujas.', instructions: 'Apunta con el ratón, haz clic para disparar. Junta 3 o más burbujas del mismo color para explotarlas.' },
      pt: { title: 'Bubble Shooter', description: 'Mire e atire bolhas para combinar 3 ou mais! Um clássico jogo de quebra-cabeça de bolhas.', instructions: 'Mire com o mouse, clique para atirar. Combine 3 ou mais bolhas da mesma cor para estourá-las.' },
    },
  },
  {
    slug: 'circlo-o-2',
    category: 'puzzle',
    iframeUrl: '/games/circloO2/index.html',
    thumbnailEmoji: '⭕',
    translations: {
      en: { title: 'circloO 2', description: 'Navigate a ball through circular mazes! A physics-based puzzle platformer.', instructions: 'Use arrow keys or drag to roll the ball. Navigate through the circular obstacles. Reach the goal to advance.' },
      es: { title: 'circloO 2', description: '¡Navega una pelota a través de laberintos circulares! Un puzzle de plataformas basado en física.', instructions: 'Usa las flechas o arrastra para rodar la pelota. Navega a través de los obstáculos circulares.' },
      pt: { title: 'circloO 2', description: 'Navegue uma bola através de labirintos circulares! Um puzzle de plataforma baseado em física.', instructions: 'Use as setas ou arraste para rolar a bola. Navegue através dos obstáculos circulares.' },
    },
  },
  {
    slug: 'dadish-3',
    category: 'action',
    iframeUrl: '/games/dadish3/index.html',
    thumbnailEmoji: '🥦',
    translations: {
      en: { title: "Dadish 3", description: "A radish dad on a quest to find his children! A charming platformer adventure.", instructions: "Use arrow keys to move and jump. Collect items and defeat enemies. Reach the end of each level." },
      es: { title: "Dadish 3", description: "¡Un padre rábano en una búsqueda para encontrar a sus hijos! Una encantadora aventura de plataformas.", instructions: "Usa las flechas para moverte y saltar. Colecciona objetos y derrota enemigos." },
      pt: { title: "Dadish 3", description: "Um rabanete pai em uma missão para encontrar seus filhos! Uma charmosa aventura de plataforma.", instructions: "Use as setas para mover e pular. Colete itens e derrote inimigos." },
    },
  },
  {
    slug: 'iron-snout',
    category: 'action',
    iframeUrl: '/games/ironsnout/index.html',
    thumbnailEmoji: '🐗',
    translations: {
      en: { title: 'Iron Snout', description: 'Fight off waves of wolves and pigs as a skilled pig! A fast-paced beat-em-up action game.', instructions: 'Use arrow keys or swipe to attack. Press towards an enemy to punch, away to kick. Survive as long as possible!' },
      es: { title: 'Iron Snout', description: '¡Defiéndete de oleadas de lobos y cerdos como un cerdo hábil! Un juego de acción rápida.', instructions: 'Usa las flechas para atacar. Presiona hacia un enemigo para golpear, lejos para patear.' },
      pt: { title: 'Iron Snout', description: 'Lute contra ondas de lobos e porcos como um porco habilidoso! Um jogo de ação rápida.', instructions: 'Use as setas para atacar. Pressione em direção a um inimigo para socar.' },
    },
  },
  {
    slug: 'ovo',
    category: 'action',
    iframeUrl: '/games/ovo/index.html',
    thumbnailEmoji: '🥚',
    translations: {
      en: { title: 'OvO', description: 'A minimalist platformer with precise controls. Run, jump, and slide through challenging levels.', instructions: 'Use arrow keys to move. Press up to jump, down to slide through gaps. Master each level\'s timing.' },
      es: { title: 'OvO', description: 'Un plataformas minimalista con controles precisos. Corre, salta y deslízate a través de niveles desafiantes.', instructions: 'Usa las flechas para moverte. Presiona arriba para saltar, abajo para deslizarte.' },
      pt: { title: 'OvO', description: 'Um plataforma minimalista com controles precisos. Corra, pule e deslize através de níveis desafiadores.', instructions: 'Use as setas para mover. Pressione cima para pular, baixo para deslizar.' },
    },
  },
  {
    slug: 'temple-of-boom',
    category: 'action',
    iframeUrl: '/games/templeofboom/index.html',
    thumbnailEmoji: '🏛️',
    translations: {
      en: { title: 'Temple of Boom', description: 'Run through ancient temples avoiding traps and collecting treasures! An endless runner adventure.', instructions: 'Swipe or use arrow keys to move left/right and jump. Dodge obstacles and collect coins.' },
      es: { title: 'Temple of Boom', description: '¡Corre a través de templos antiguos evitando trampas y coleccionando tesoros! Una aventura sin fin.', instructions: 'Desliza o usa las flechas para moverte izquierda/derecha y saltar. Esquiva obstáculos.' },
      pt: { title: 'Temple of Boom', description: 'Corra através de templos antigos evitando armadilhas e coletando tesouros! Uma aventura sem fim.', instructions: 'Deslize ou use as setas para mover esquerda/direita e pular. Desvie de obstáculos.' },
    },
  },
  {
    slug: 'eggy-car',
    category: 'casual',
    iframeUrl: '/games/eggycar/index.html',
    thumbnailEmoji: '🥚',
    translations: {
      en: { title: 'Eggy Car', description: 'Drive a car while carrying a fragile egg! A fun physics-based driving game.', instructions: 'Use arrow keys to drive. Balance the car to keep the egg from falling. Reach the finish line intact!' },
      es: { title: 'Eggy Car', description: '¡Conduce un coche mientras llevas un huevo frágil! Un divertido juego de conducción basado en física.', instructions: 'Usa las flechas para conducir. Equilibra el coche para que el huevo no se caiga.' },
      pt: { title: 'Eggy Car', description: 'Dirija um carro enquanto carrega um ovo frágil! Um divertido jogo de direção baseado em física.', instructions: 'Use as setas para dirigir. Equilibre o carro para evitar que o ovo caia.' },
    },
  },
];
